### ISSUE TITLE
Create the UX Rubric

### ISSUE THREAD

**Issue by kaikeekat** [wearther/weather-app#2]
@martaannap @JennMV

**Comment by martaannap** [comment]
| | 0 points | 1 points | 2 points | 3 points |
| --- | --- | --- | --- | --- |
| **Research** | No research | Just the basics: minimal research | Research pertaining to some of the categories | Detailed research about competition (design and function) and user audience |
| **Teamwork** | No contribution to team | Minimal or inconsistent contribution to teamwork | Decent amount of contribution | All contribute to all parts of the project, working together to create wireframes, design and constructive feedback on work |
| **Design** | Minimal design, boring | Generic design | Quality design with unique and interesting content | Unique and visually pleasing design  with engaging content and cohesive look |
| **Personas** | No personas created | Basic personas | Developed personas are relevant and give a little bit of insight into users | Gives great and detailed insight into the users needs, helps the app design better appeal to users |

**Comment by kaikeekat** [comment]
Research: 3 Points. We thoroughly researched the current market and defined a specific target audience.
Teamwork: 2 Points. Could have worked a bit harder but we got everything done, and just general communication.
Design: 3 Points. Good consistent look.
Personas: 3 Points. 3 Detailed personas.
