### ISSUE TITLE
Create the Code Rubric

### ISSUE THREAD

**Issue by kaikeekat** [wearther/weather-app#3]
@martaannap @JennMV

**Comment by martaannap** [comment]
| | 0 points | 1 points | 2 points | 3 points |
| --- | --- | --- | --- | --- |
| **Accessibility** | No considerations | Added some alt attributes, nothing else | Just the basics: alt attributes, roles | Accessibility is well considered and tested |
| **Teamwork** | No contribution to team | Minimal contribution to teamwork | Decent but inconsistent contribution to teamwork | All contribute to all parts of the project, working together to fix bugs, giving constructive feedback on work |
| **Coding best practices** | No consideration | Decent adherence to naming-conventions and | Committed frequently and properly, correct indentation practices| All code follows the naming conventions. Naming-conventions are all consistent. Code is clean and organized. Keeping branches separated for separate issues, closing them properly when they are finished. |
| **Responsiveness** | Not responsive | Works well on some but not all screens | Responsive but with a few inconsistencies | All screens are responsive and readable at different screen sizes |
| **Performance** | Slow as a turtle | Slow | Could load faster | Loads super fast |

**Comment by kaikeekat** [comment]
**Accessibility**
1/3
Added some of the meta data facebook open graph.
**Teamwork**
2/3
Had good communication but were preoccupied with other projects. Could have improved on communication outside of class.
**Coding best practices**
3/3
We killed it. No one was too disoriented looking at eachothers coding.
**Responsiveness**
3/3
We worked very hard to make sure that the page was responsive from the very beginning.
**Performance**
3/3
Our webpage loaded in under a second.
