### ISSUE TITLE
Personas

### ISSUE THREAD

**Issue by kaikeekat** [wearther/weather-app#4]

**Comment by kaikeekat** [comment]
![untitled user persona](https://user-images.githubusercontent.com/16653321/35241002-19eddfa2-ff83-11e7-8d4d-6a6f556f2f16.png)

**Comment by JennMV** [comment]
<img width="601" alt="persona 2" src="https://user-images.githubusercontent.com/16690604/35490340-08052f54-046d-11e8-819f-dcee17d29afc.png">
